#include <iostream>
#include "sortting.h"
#include "AlgorithmMode.h"
#include "generateData.h"
#include <cstring>
#include <cstdlib>
#include <ctime>
#include <cstdlib>
#include <thread>
#include <chrono>
#include <iomanip>
